// List of major US cities by population (includes top 200+ cities)
export const US_CITIES = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", 
  "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", 
  "San Francisco", "Seattle", "Denver", "Washington DC", "Boston", "El Paso", "Nashville", "Detroit", 
  "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", 
  "Tucson", "Fresno", "Sacramento", "Mesa", "Atlanta", "Kansas City", "Colorado Springs", "Omaha", 
  "Raleigh", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tampa", "Tulsa", 
  "Arlington", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu", 
  "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Henderson", "Stockton", "Saint Paul", 
  "Cincinnati", "St. Louis", "Pittsburgh", "Greensboro", "Lincoln", "Anchorage", "Plano", "Orlando", 
  "Irvine", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne", "St. Petersburg", "Laredo", 
  "Jersey City", "Chandler", "Madison", "Lubbock", "Scottsdale", "Reno", "Buffalo", "Gilbert", 
  "Glendale", "North Las Vegas", "Winston-Salem", "Chesapeake", "Norfolk", "Fremont", "Garland", 
  "Irving", "Hialeah", "Richmond", "Boise", "Spokane", "Tacoma", "Modesto", "Fontana", "Des Moines", 
  "Moreno Valley", "Fayetteville", "Frisco", "McKinney", "Rochester", "Port St. Lucie", "Oxnard", 
  "Salt Lake City", "Montgomery", "Amarillo", "Huntington Beach", "Little Rock", "Augusta", "Grand Rapids", 
  "Columbus", "Yonkers", "Akron", "Huntsville", "Grand Prairie", "Overland Park", "Tallahassee", 
  "Knoxville", "Brownsville", "Worcester", "Newport News", "Santa Clarita", "Providence", "Fort Lauderdale", 
  "Chattanooga", "Oceanside", "Garden Grove", "Rancho Cucamonga", "Tempe", "Ontario", "Vancouver", 
  "Springfield", "Pembroke Pines", "Elk Grove", "Salem", "Eugene", "Corona", "Peoria", "Sioux Falls", 
  "Lancaster", "Alexandria", "Hayward", "Lakewood", "Palmdale", "Salinas", "Springfield", "Sunnyvale", 
  "Hollywood", "Pomona", "Kansas City", "Escondido", "Pasadena", "Joliet", "Paterson", "Naperville", 
  "Bellevue", "Bridgeport", "Rockford", "Torrance", "Savannah", "Killeen", "McAllen", "Syracuse", 
  "Surprise", "Denton", "Roseville", "Thornton", "Miramar", "Pasadena", "Mesquite", "Olathe", 
  "Dayton", "Carrollton", "Waco", "Orange", "Fullerton", "Charleston", "West Valley City", "Visalia", 
  "Hampton", "Gainesville", "Warren", "Coral Springs", "Cedar Rapids", "Round Rock", "Sterling Heights", 
  "Kent", "Columbia", "Santa Clara", "New Haven", "Stamford", "Concord", "Elizabeth", "Athens", 
  "Berkeley", "Ann Arbor", "Murfreesboro", "Lansing", "Evansville", "Hartford", "Lafayette", "Midland", 
  "Lowell", "Norman", "Provo", "Albany", "Baton Rouge", "Memphis", "Boulder", "Nashville", "Fort Collins",
  "San Mateo", "Cary", "Santa Fe", "Orlando", "Tampa Bay", "Charlotte", "Cambridge", "Wichita Falls",
  "Wilmington", "South Bend", "Green Bay", "Burbank", "Carlsbad", "Tuscaloosa", "Clearwater",
  "Manchester", "Bend", "Macon", "Mobile", "Roanoke", "Allentown", "Olympia", "Asheville", "Tallahassee"
];