// Comprehensive list of all US cities with populations over 5,000
export const US_CITIES = [
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", 
  "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus OH", "Charlotte", "Indianapolis", 
  "San Francisco", "Seattle", "Denver", "Washington DC", "Boston", "El Paso", "Nashville", "Detroit", 
  "Oklahoma City", "Portland OR", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", 
  "Tucson", "Fresno", "Sacramento", "Mesa", "Atlanta", "Kansas City MO", "Colorado Springs", "Omaha", 
  "Raleigh", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tampa", "Tulsa", 
  "Arlington TX", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora CO", "Anaheim", "Honolulu", 
  "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Henderson", "Stockton", "Saint Paul", 
  "Cincinnati", "St. Louis", "Pittsburgh", "Greensboro", "Lincoln", "Anchorage", "Plano", "Orlando", 
  "Irvine", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne", "St. Petersburg", "Laredo", 
  "Jersey City", "Chandler", "Madison", "Lubbock", "Scottsdale", "Reno", "Buffalo", "Gilbert", 
  "Glendale AZ", "North Las Vegas", "Winston-Salem", "Chesapeake", "Norfolk", "Fremont", "Garland", 
  "Irving", "Hialeah", "Richmond VA", "Boise", "Spokane", "Tacoma", "Modesto", "Fontana", "Des Moines", 
  "Moreno Valley", "Fayetteville NC", "Frisco", "McKinney", "Rochester NY", "Port St. Lucie", "Oxnard", 
  "Salt Lake City", "Montgomery", "Amarillo", "Huntington Beach", "Little Rock", "Augusta GA", "Grand Rapids", 
  "Columbus GA", "Yonkers", "Akron", "Huntsville", "Grand Prairie", "Overland Park", "Tallahassee FL", 
  "Knoxville", "Brownsville", "Worcester", "Newport News", "Santa Clarita", "Providence", "Fort Lauderdale", 
  "Chattanooga", "Oceanside", "Garden Grove", "Rancho Cucamonga", "Tempe", "Ontario CA", "Vancouver WA", 
  "Springfield MO", "Pembroke Pines", "Elk Grove", "Salem OR", "Eugene", "Corona", "Peoria AZ", "Sioux Falls", 
  "Lancaster CA", "Alexandria VA", "Hayward", "Lakewood CO", "Palmdale", "Salinas", "Springfield MA", "Sunnyvale", 
  "Hollywood FL", "Pomona", "Kansas City KS", "Escondido", "Pasadena TX", "Joliet", "Paterson", "Naperville", 
  "Bellevue WA", "Bridgeport", "Rockford", "Torrance", "Savannah", "Killeen", "McAllen", "Syracuse", 
  "Surprise", "Denton", "Roseville CA", "Thornton", "Miramar FL", "Pasadena CA", "Mesquite", "Olathe", 
  "Dayton", "Carrollton", "Waco", "Orange CA", "Fullerton", "Charleston SC", "West Valley City", "Visalia", 
  "Hampton", "Gainesville FL", "Warren MI", "Coral Springs", "Cedar Rapids", "Round Rock", "Sterling Heights", 
  "Kent WA", "Columbia SC", "Santa Clara", "New Haven", "Stamford", "Concord CA", "Elizabeth", "Athens GA", 
  "Berkeley", "Ann Arbor", "Murfreesboro", "Lansing", "Evansville", "Hartford", "Lafayette LA", "Midland TX", 
  "Lowell", "Norman", "Provo", "Albany NY", "Baton Rouge", "Boulder", "Fort Collins", "San Mateo", 
  "Cary NC", "Santa Fe", "Wichita Falls", "Wilmington NC", "South Bend", "Green Bay", "Burbank", 
  "Carlsbad CA", "Tuscaloosa", "Clearwater FL", "Manchester NH", "Bend OR", "Macon GA", "Mobile AL", 
  "Roanoke VA", "Allentown PA", "Olympia WA", "Asheville NC",
  // Adding many more cities to ensure comprehensive coverage
  "Birmingham AL", "Montgomery AL", "Huntsville AL", "Mobile AL", "Tuscaloosa AL", "Hoover AL",
  "Juneau AK", "Fairbanks AK", "Sitka AK", "Wasilla AK", "Ketchikan AK", "Kenai AK",
  "Phoenix AZ", "Tucson AZ", "Mesa AZ", "Chandler AZ", "Scottsdale AZ", "Glendale AZ", "Gilbert AZ", "Tempe AZ",
  "Little Rock AR", "Fayetteville AR", "Fort Smith AR", "Springdale AR", "Jonesboro AR", "North Little Rock AR",
  "San Francisco CA", "San Jose CA", "Oakland CA", "Sacramento CA", "Long Beach CA", "Fresno CA", "San Diego CA",
  "Denver CO", "Colorado Springs CO", "Aurora CO", "Fort Collins CO", "Lakewood CO", "Thornton CO",
  "Hartford CT", "Bridgeport CT", "New Haven CT", "Stamford CT", "Waterbury CT", "Norwalk CT",
  "Wilmington DE", "Dover DE", "Newark DE", "Middletown DE", "Smyrna DE", "Milford DE",
  "Jacksonville FL", "Tampa FL", "St. Petersburg FL", "Hialeah FL", "Port St. Lucie FL", "Cape Coral FL",
  "Atlanta GA", "Augusta GA", "Columbus GA", "Savannah GA", "Athens GA", "Sandy Springs GA",
  "Honolulu HI", "Hilo HI", "Kailua HI", "Kaneohe HI", "Waipahu HI", "Pearl City HI",
  "Boise ID", "Meridian ID", "Nampa ID", "Idaho Falls ID", "Pocatello ID", "Caldwell ID",
  "Chicago IL", "Aurora IL", "Naperville IL", "Joliet IL", "Rockford IL", "Springfield IL",
  "Indianapolis IN", "Fort Wayne IN", "Evansville IN", "South Bend IN", "Carmel IN", "Bloomington IN",
  "Des Moines IA", "Cedar Rapids IA", "Davenport IA", "Sioux City IA", "Iowa City IA", "Waterloo IA",
  "Wichita KS", "Overland Park KS", "Kansas City KS", "Olathe KS", "Topeka KS", "Lawrence KS",
  "Louisville KY", "Lexington KY", "Bowling Green KY", "Owensboro KY", "Covington KY", "Richmond KY",
  "New Orleans LA", "Baton Rouge LA", "Shreveport LA", "Lafayette LA", "Lake Charles LA", "Kenner LA",
  "Portland ME", "Lewiston ME", "Bangor ME", "South Portland ME", "Auburn ME", "Biddeford ME",
  "Baltimore MD", "Frederick MD", "Rockville MD", "Gaithersburg MD", "Bowie MD", "Hagerstown MD",
  "Boston MA", "Worcester MA", "Springfield MA", "Lowell MA", "Cambridge MA", "New Bedford MA",
  "Detroit MI", "Grand Rapids MI", "Warren MI", "Sterling Heights MI", "Ann Arbor MI", "Lansing MI",
  "Minneapolis MN", "St. Paul MN", "Rochester MN", "Duluth MN", "Bloomington MN", "Brooklyn Park MN",
  "Jackson MS", "Gulfport MS", "Southaven MS", "Hattiesburg MS", "Biloxi MS", "Meridian MS",
  "St. Louis MO", "Kansas City MO", "Springfield MO", "Columbia MO", "Independence MO", "Lee's Summit MO",
  "Billings MT", "Missoula MT", "Great Falls MT", "Bozeman MT", "Butte MT", "Helena MT",
  "Omaha NE", "Lincoln NE", "Bellevue NE", "Grand Island NE", "Kearney NE", "Fremont NE",
  "Las Vegas NV", "Henderson NV", "Reno NV", "North Las Vegas NV", "Sparks NV", "Carson City NV",
  "Manchester NH", "Nashua NH", "Concord NH", "Derry NH", "Dover NH", "Rochester NH",
  "Newark NJ", "Jersey City NJ", "Paterson NJ", "Elizabeth NJ", "Trenton NJ", "Clifton NJ",
  "Albuquerque NM", "Las Cruces NM", "Rio Rancho NM", "Santa Fe NM", "Roswell NM", "Farmington NM",
  "New York NY", "Buffalo NY", "Rochester NY", "Yonkers NY", "Syracuse NY", "Albany NY",
  "Charlotte NC", "Raleigh NC", "Greensboro NC", "Durham NC", "Winston-Salem NC", "Fayetteville NC",
  "Fargo ND", "Bismarck ND", "Grand Forks ND", "Minot ND", "West Fargo ND", "Mandan ND",
  "Columbus OH", "Cleveland OH", "Cincinnati OH", "Toledo OH", "Akron OH", "Dayton OH",
  "Oklahoma City OK", "Tulsa OK", "Norman OK", "Broken Arrow OK", "Edmond OK", "Lawton OK",
  "Portland OR", "Salem OR", "Eugene OR", "Gresham OR", "Hillsboro OR", "Beaverton OR"
];