// US cities with populations over 1,000 (abbreviated list)
export interface USCity {
  city: string;
  state: string;
}

export const US_CITIES: USCity[] = [
  // Major Metropolitan Areas
  { city: "New York", state: "NY" },
  { city: "Los Angeles", state: "CA" },
  { city: "Chicago", state: "IL" },
  { city: "Houston", state: "TX" },
  { city: "Phoenix", state: "AZ" },
  { city: "Philadelphia", state: "PA" },
  { city: "San Antonio", state: "TX" },
  { city: "San Diego", state: "CA" },
  { city: "Dallas", state: "TX" },
  { city: "San Jose", state: "CA" },
  { city: "Austin", state: "TX" },
  { city: "Jacksonville", state: "FL" },
  { city: "Fort Worth", state: "TX" },
  { city: "Columbus", state: "OH" },
  { city: "Charlotte", state: "NC" },
  { city: "Indianapolis", state: "IN" },
  { city: "San Francisco", state: "CA" },
  { city: "Seattle", state: "WA" },
  { city: "Denver", state: "CO" },
  { city: "Washington", state: "DC" },
  { city: "Boston", state: "MA" },
  { city: "El Paso", state: "TX" },
  { city: "Nashville", state: "TN" },
  { city: "Detroit", state: "MI" },
  { city: "Oklahoma City", state: "OK" },
  { city: "Portland", state: "OR" },
  { city: "Las Vegas", state: "NV" },
  { city: "Memphis", state: "TN" },
  { city: "Louisville", state: "KY" },
  { city: "Baltimore", state: "MD" },
  { city: "Milwaukee", state: "WI" },
  { city: "Albuquerque", state: "NM" },
  { city: "Tucson", state: "AZ" },
  { city: "Fresno", state: "CA" },
  { city: "Sacramento", state: "CA" },
  { city: "Mesa", state: "AZ" },
  { city: "Atlanta", state: "GA" },
  { city: "Kansas City", state: "MO" },
  { city: "Colorado Springs", state: "CO" },
  { city: "Omaha", state: "NE" },
  { city: "Raleigh", state: "NC" },
  { city: "Miami", state: "FL" },
  { city: "Long Beach", state: "CA" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Oakland", state: "CA" },
  { city: "Minneapolis", state: "MN" },
  { city: "Tampa", state: "FL" },
  { city: "Tulsa", state: "OK" },
  
  // Medium Cities
  { city: "Arlington", state: "TX" },
  { city: "New Orleans", state: "LA" },
  { city: "Wichita", state: "KS" },
  { city: "Cleveland", state: "OH" },
  { city: "Bakersfield", state: "CA" },
  { city: "Aurora", state: "CO" },
  { city: "Anaheim", state: "CA" },
  { city: "Honolulu", state: "HI" },
  { city: "Santa Ana", state: "CA" },
  { city: "Riverside", state: "CA" },
  { city: "Corpus Christi", state: "TX" },
  { city: "Lexington", state: "KY" },
  { city: "Henderson", state: "NV" },
  { city: "Stockton", state: "CA" },
  { city: "Saint Paul", state: "MN" },
  { city: "Cincinnati", state: "OH" },
  { city: "St. Louis", state: "MO" },
  { city: "Pittsburgh", state: "PA" },
  { city: "Greensboro", state: "NC" },
  { city: "Lincoln", state: "NE" },
  { city: "Anchorage", state: "AK" },
  { city: "Plano", state: "TX" },
  { city: "Orlando", state: "FL" },
  { city: "Irvine", state: "CA" },
  { city: "Newark", state: "NJ" },
  { city: "Durham", state: "NC" },
  { city: "Chula Vista", state: "CA" },
  { city: "Toledo", state: "OH" },
  { city: "Fort Wayne", state: "IN" },
  { city: "St. Petersburg", state: "FL" },
  { city: "Laredo", state: "TX" },
  { city: "Jersey City", state: "NJ" },
  { city: "Chandler", state: "AZ" },
  { city: "Madison", state: "WI" },
  { city: "Lubbock", state: "TX" },
  { city: "Scottsdale", state: "AZ" },
  { city: "Reno", state: "NV" },
  { city: "Buffalo", state: "NY" },
  { city: "Gilbert", state: "AZ" },
  
  // Smaller Cities
  { city: "Brownsville", state: "TX" },
  { city: "Worcester", state: "MA" },
  { city: "Newport News", state: "VA" },
  { city: "Santa Clarita", state: "CA" },
  { city: "Providence", state: "RI" },
  { city: "Fort Lauderdale", state: "FL" },
  { city: "Chattanooga", state: "TN" },
  { city: "Oceanside", state: "CA" },
  { city: "Garden Grove", state: "CA" },
  { city: "Rancho Cucamonga", state: "CA" },
  { city: "Tempe", state: "AZ" },
  { city: "Ontario", state: "CA" },
  { city: "Vancouver", state: "WA" },
  { city: "Cape Coral", state: "FL" },
  { city: "Sioux Falls", state: "SD" },
  { city: "Springfield", state: "MO" },
  { city: "Peoria", state: "IL" },
  { city: "Pembroke Pines", state: "FL" },
  { city: "Elk Grove", state: "CA" },
  { city: "Salem", state: "OR" },
  { city: "Lancaster", state: "CA" },
  { city: "Corona", state: "CA" },
  { city: "Eugene", state: "OR" },
  { city: "Palmdale", state: "CA" },
  { city: "Salinas", state: "CA" },
  { city: "Pasadena", state: "TX" },
  { city: "Fort Collins", state: "CO" },
  { city: "Hayward", state: "CA" },
  { city: "Pomona", state: "CA" },
  { city: "Cary", state: "NC" },
  
  // Additional cities
  { city: "Aberdeen", state: "SD" },
  { city: "Abilene", state: "TX" },
  { city: "Albany", state: "NY" },
  { city: "Alexandria", state: "VA" },
  { city: "Allentown", state: "PA" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Appleton", state: "WI" },
  { city: "Arlington", state: "VA" },
  { city: "Asheville", state: "NC" },
  { city: "Athens", state: "GA" },
  { city: "Atlantic City", state: "NJ" },
  { city: "Augusta", state: "GA" },
  { city: "Berkeley", state: "CA" },
  { city: "Bethesda", state: "MD" },
  { city: "Birmingham", state: "AL" },
  { city: "Bloomington", state: "IN" },
  { city: "Boise", state: "ID" },
  { city: "Boulder", state: "CO" },
  { city: "Bozeman", state: "MT" },
  { city: "Bridgeport", state: "CT" },
  { city: "Burlington", state: "VT" },
  { city: "Cambridge", state: "MA" },
  { city: "Charleston", state: "SC" },
  { city: "Charlottesville", state: "VA" },
  { city: "Dayton", state: "OH" },
  { city: "Des Moines", state: "IA" },
  { city: "Flagstaff", state: "AZ" },
  { city: "Grand Rapids", state: "MI" },
  { city: "Hartford", state: "CT" },
  { city: "Hollywood", state: "FL" },
  { city: "Jackson", state: "MS" },
  { city: "Knoxville", state: "TN" },
  { city: "Montgomery", state: "AL" },
  { city: "Nashville", state: "TN" },
  { city: "New Haven", state: "CT" },
  { city: "Olympia", state: "WA" },
  { city: "Palo Alto", state: "CA" },
  { city: "Pensacola", state: "FL" },
  { city: "Portland", state: "ME" },
  { city: "Provo", state: "UT" },
  { city: "Salt Lake City", state: "UT" },
  { city: "San Luis Obispo", state: "CA" },
  { city: "Santa Barbara", state: "CA" },
  { city: "Santa Fe", state: "NM" },
  { city: "Sarasota", state: "FL" },
  { city: "Vero Beach", state: "FL" },
  { city: "Jupiter", state: "FL" },
  { city: "West Palm Beach", state: "FL" },
  { city: "Naples", state: "FL" },
  { city: "Fort Myers", state: "FL" },
  { city: "Boca Raton", state: "FL" },
  { city: "Clearwater", state: "FL" },
  { city: "Gainesville", state: "FL" },
  { city: "Delray Beach", state: "FL" },
  { city: "Lakeland", state: "FL" },
  { city: "Davie", state: "FL" },
  { city: "Melbourne", state: "FL" },
  { city: "Daytona Beach", state: "FL" },
  { city: "Stuart", state: "FL" },
  { city: "Savannah", state: "GA" },
  { city: "Spokane", state: "WA" },
  { city: "Syracuse", state: "NY" },
  { city: "Charleston", state: "SC" },
  { city: "Myrtle Beach", state: "SC" },
  { city: "Asheville", state: "NC" },
  { city: "Santa Monica", state: "CA" },
  { city: "Beverly Hills", state: "CA" },
  { city: "Princeton", state: "NJ" },
  { city: "New Haven", state: "CT" },
  { city: "Ann Arbor", state: "MI" },
  { city: "Tallahassee", state: "FL" },
  { city: "Trenton", state: "NJ" },
  
  // Virginia cities with population over 1,000
  { city: "Alexandria", state: "VA" },
  { city: "Arlington", state: "VA" },
  { city: "Ashland", state: "VA" },
  { city: "Blacksburg", state: "VA" },
  { city: "Bristol", state: "VA" },
  { city: "Charlottesville", state: "VA" },
  { city: "Chesapeake", state: "VA" },
  { city: "Christiansburg", state: "VA" },
  { city: "Colonial Heights", state: "VA" },
  { city: "Culpeper", state: "VA" },
  { city: "Danville", state: "VA" },
  { city: "Fairfax", state: "VA" },
  { city: "Falls Church", state: "VA" },
  { city: "Farmville", state: "VA" },
  { city: "Fredericksburg", state: "VA" },
  { city: "Front Royal", state: "VA" },
  { city: "Hampton", state: "VA" },
  { city: "Harrisonburg", state: "VA" },
  { city: "Herndon", state: "VA" },
  { city: "Leesburg", state: "VA" },
  { city: "Lexington", state: "VA" },
  { city: "Lynchburg", state: "VA" },
  { city: "Manassas", state: "VA" },
  { city: "Manassas Park", state: "VA" },
  { city: "Martinsville", state: "VA" },
  { city: "Newport News", state: "VA" },
  { city: "Norfolk", state: "VA" },
  { city: "Petersburg", state: "VA" },
  { city: "Portsmouth", state: "VA" },
  { city: "Pulaski", state: "VA" },
  { city: "Radford", state: "VA" },
  { city: "Richmond", state: "VA" },
  { city: "Roanoke", state: "VA" },
  { city: "Salem", state: "VA" },
  { city: "Staunton", state: "VA" },
  { city: "Suffolk", state: "VA" },
  { city: "Vienna", state: "VA" },
  { city: "Virginia Beach", state: "VA" },
  { city: "Waynesboro", state: "VA" },
  { city: "Williamsburg", state: "VA" },
  { city: "Winchester", state: "VA" },
  { city: "Abingdon", state: "VA" },
  { city: "Altavista", state: "VA" },
  { city: "Bedford", state: "VA" },
  { city: "Berryville", state: "VA" },
  { city: "Big Stone Gap", state: "VA" },
  { city: "Blackstone", state: "VA" },
  { city: "Bluefield", state: "VA" },
  { city: "Bridgewater", state: "VA" },
  { city: "Buena Vista", state: "VA" },
  { city: "Clifton Forge", state: "VA" },
  { city: "Covington", state: "VA" },
  { city: "Dumfries", state: "VA" },
  { city: "Emporia", state: "VA" },
  { city: "Galax", state: "VA" },
  { city: "Gate City", state: "VA" },
  { city: "Glasgow", state: "VA" },
  { city: "Gordonsville", state: "VA" },
  { city: "Grundy", state: "VA" },
  { city: "Marion", state: "VA" },
  { city: "Middleburg", state: "VA" },
  { city: "Middletown", state: "VA" },
  { city: "Narrows", state: "VA" },
  { city: "New Market", state: "VA" },
  { city: "Norton", state: "VA" },
  { city: "Occoquan", state: "VA" },
  { city: "Onancock", state: "VA" },
  { city: "Orange", state: "VA" },
  { city: "Pearisburg", state: "VA" },
  { city: "Pennington Gap", state: "VA" },
  { city: "Purcellville", state: "VA" },
  { city: "Quantico", state: "VA" },
  { city: "Richlands", state: "VA" },
  { city: "Rocky Mount", state: "VA" },
  { city: "South Boston", state: "VA" },
  { city: "South Hill", state: "VA" },
  { city: "Strasburg", state: "VA" },
  { city: "Tappahannock", state: "VA" },
  { city: "Vinton", state: "VA" },
  { city: "Warrenton", state: "VA" },
  { city: "Wise", state: "VA" },
  { city: "Woodstock", state: "VA" },
  { city: "Wytheville", state: "VA" }
];