// US cities with populations over 1,000 (comprehensive list)
export const US_CITIES = [
  // Major Metropolitan Areas (1M+)
  "New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", "San Antonio", "San Diego", 
  "Dallas", "San Jose", "Austin", "Jacksonville", "Fort Worth", "Columbus", "Charlotte", "Indianapolis", 
  "San Francisco", "Seattle", "Denver", "Washington DC", "Boston", "El Paso", "Nashville", "Detroit", 
  "Oklahoma City", "Portland", "Las Vegas", "Memphis", "Louisville", "Baltimore", "Milwaukee", "Albuquerque", 
  "Tucson", "Fresno", "Sacramento", "Mesa", "Atlanta", "Kansas City", "Colorado Springs", "Omaha", 
  "Raleigh", "Miami", "Long Beach", "Virginia Beach", "Oakland", "Minneapolis", "Tampa", "Tulsa", 
  
  // Medium Cities (100k-1M)
  "Arlington", "New Orleans", "Wichita", "Cleveland", "Bakersfield", "Aurora", "Anaheim", "Honolulu", 
  "Santa Ana", "Riverside", "Corpus Christi", "Lexington", "Henderson", "Stockton", "Saint Paul", 
  "Cincinnati", "St. Louis", "Pittsburgh", "Greensboro", "Lincoln", "Anchorage", "Plano", "Orlando", 
  "Irvine", "Newark", "Durham", "Chula Vista", "Toledo", "Fort Wayne", "St. Petersburg", "Laredo", 
  "Jersey City", "Chandler", "Madison", "Lubbock", "Scottsdale", "Reno", "Buffalo", "Gilbert", 
  
  // Small Cities (25k-100k)
  "Glendale", "North Las Vegas", "Winston-Salem", "Chesapeake", "Norfolk", "Fremont", "Garland", 
  "Irving", "Hialeah", "Richmond", "Boise", "Spokane", "Tacoma", "Modesto", "Fontana", "Des Moines", 
  "Moreno Valley", "Fayetteville", "Frisco", "McKinney", "Rochester", "Port St. Lucie", "Oxnard", 
  "Salt Lake City", "Montgomery", "Amarillo", "Huntington Beach", "Little Rock", "Augusta", "Grand Rapids", 
  "Yonkers", "Akron", "Huntsville", "Grand Prairie", "Overland Park", "Tallahassee", "Knoxville", 
  
  // Smaller Cities and Towns (5k-25k)
  "Brownsville", "Worcester", "Newport News", "Santa Clarita", "Providence", "Fort Lauderdale", 
  "Chattanooga", "Oceanside", "Garden Grove", "Rancho Cucamonga", "Tempe", "Ontario", "Vancouver", 
  "Cape Coral", "Sioux Falls", "Springfield", "Peoria", "Pembroke Pines", "Elk Grove", "Salem", "Lancaster", 
  "Corona", "Eugene", "Palmdale", "Salinas", "Pasadena", "Fort Collins", "Hayward", "Pomona", "Cary",
  
  // Cities 1k-5k population
  "Aberdeen", "Abilene", "Ada", "Adalanto", "Adrian", "Akron", "Alameda", "Albany", "Albert Lea", "Albion", 
  "Albuquerque", "Alexandria", "Allegan", "Allen", "Allendale", "Allentown", "Alliance", "Alma", "Alpena", 
  "Alpine", "Altus", "Alvin", "Amarillo", "Amherst", "Anaheim", "Anchorage", "Anderson", "Andersonville", 
  "Andover", "Ann Arbor", "Annandale", "Antioch", "Apache Junction", "Apex", "Apopka", "Appleton", "Arcadia", 
  "Ardmore", "Arkansas City", "Arlington", "Arlington Heights", "Arvada", "Asheville", "Ashland", "Ashtabula", 
  "Astoria", "Atchison", "Athens", "Atlanta", "Atlantic City", "Atwater", "Auburn", "Augusta", "Aurora", 
  "Austin", "Avon Lake", "Avondale", "Aztec", "Bakersfield", "Baldwin", "Baltimore", "Bangor", "Baraboo", 
  "Barberton", "Bardstown", "Bartlesville", "Batavia", "Baton Rouge", "Battle Creek", "Bay City", "Bayonne", 
  "Baytown", "Beaufort", "Beaumont", "Beavercreek", "Beaverton", "Bedford", "Belleville", "Bellflower", 
  "Bellingham", "Belmont", "Beloit", "Bemidji", "Benicia", "Bennington", "Benton", "Benton Harbor", "Berea", 
  "Berkeley", "Berlin", "Berwyn", "Bethel", "Bethesda", "Bethlehem", "Beverly", "Beverly Hills", "Billings", 
  "Biloxi", "Binghamton", "Birmingham", "Bismarck", "Blacksburg", "Bloomfield", "Bloomington", "Blue Springs", 
  "Bluefield", "Boca Raton", "Bogalusa", "Boise", "Bonita Springs", "Boone", "Boonville", "Bossier City", 
  "Boston", "Boulder", "Bountiful", "Bowling Green", "Boynton Beach", "Bozeman", "Bradenton", "Bradford", 
  "Brainerd", "Brandon", "Branson", "Brea", "Bremerton", "Brentwood", "Brevard", "Brewster", "Bridgeport", 
  "Bristol", "Brockton", "Broken Arrow", "Brookfield", "Brookhaven", "Brookings", "Brookline", "Brooklyn", 
  "Brooklyn Park", "Brownsville", "Brunswick", "Bryan", "Bucyrus", "Buffalo", "Burbank", "Burlington", 
  "Burnsville", "Butler", "Butte", "Cadillac", "Cairo", "Caldwell", "Cambridge", "Camden", "Campbell", 
  "Canton", "Cape Coral", "Cape Girardeau", "Cape May", "Carbondale", "Carlsbad", "Carmel", "Carmichael", 
  "Carol Stream", "Carpentersville", "Carrollton", "Carson", "Carson City", "Carthage", "Cary", "Casa Grande", 
  "Casper", "Castle Rock", "Cedar Falls", "Cedar Rapids", "Centerville", "Centralia", "Ceres", "Cerritos", 
  "Chambersburg", "Champaign", "Chandler", "Chapel Hill", "Charleston", "Charlotte", "Charlottesville", 
  "Chattanooga", "Chesterfield", "Cheyenne", "Chicago", "Chico", "Chicopee", "Chino", "Chula Vista", 
  "Cincinnati", "Circleville", "Claremont", "Clarksburg", "Clarksville", "Clayton", "Clearfield", "Clearwater", 
  "Cleveland", "Cleveland Heights", "Clifton", "Climax", "Clinton", "Clovis", "Coachella", "Coatesville", 
  "Cocoa", "Coeur d'Alene", "College Park", "College Station", "Collinsville", "Colorado Springs", "Columbia", 
  "Columbus", "Compton", "Concord", "Conroe", "Conway", "Coon Rapids", "Cooper City", "Copperas Cove", 
  "Coral Gables", "Coral Springs", "Corona", "Corpus Christi", "Corvallis", "Costa Mesa", "Cottage Grove", 
  "Council Bluffs", "Country Club Hills", "Coventry", "Covington", "Cranston", "Crestview", "Crestwood", 
  "Cripple Creek", "Crystal Lake", "Culver City", "Cumberland", "Cuyahoga Falls", "Cypress", "Dallas", 
  "Dalton", "Daly City", "Danbury", "Danville", "Darien", "Davenport", "Davidson", "Davis", "Dayton", 
  "Daytona Beach", "Dearborn", "Dearborn Heights", "Decatur", "Deerfield", "Defiance", "DeKalb", "Delaware", 
  "Delray Beach", "Del Rio", "Delta", "Denison", "Dennis", "Denton", "Denver", "Derby", "Des Moines", 
  "Des Plaines", "Detroit", "Diamond Bar", "Dickinson", "Dodge City", "Dothan", "Douglas", "Dover", "Downey", 
  "Doylestown", "Driggs", "Dubuque", "Duluth", "Duncan", "Dunkirk", "Dunn", "Durham", "Dyersburg", "Eagle", 
  "Eagle Pass", "East Chicago", "East Hartford", "East Haven", "East Lansing", "East Liverpool", "East Peoria", 
  "East Providence", "East St. Louis", "Easton", "Eastpointe", "Eau Claire", "Eden Prairie", "Edina", "Edison", 
  "Edmond", "Edmonds", "El Cajon", "El Centro", "El Dorado", "El Monte", "El Paso", "El Segundo", "Elgin", 
  "Elizabeth", "Elizabethtown", "Elk Grove", "Elkhart", "Elko", "Ellensburg", "Ellsworth", "Elmhurst", "Elmira", 
  "Elon", "Elwood", "Ely", "Emporia", "Encinitas", "Enfield", "Englewood", "Enid", "Enterprise", "Erie", 
  "Erlanger", "Escanaba", "Escondido", "Espanola", "Essex", "Euclid", "Eugene", "Eureka", "Eustis", "Evanston", 
  "Evansville", "Everett", "Excelsior Springs", "Fairbanks", "Fairfax", "Fairfield", "Fall River", "Fallon", 
  "Falls Church", "Faribault", "Farmington", "Fargo", "Fayetteville", "Federal Way", "Fernandina Beach", 
  "Ferndale", "Findlay", "Fitchburg", "Flagstaff", "Flint", "Florence", "Florida City", "Fond du Lac", 
  "Forest Grove", "Forest Hills", "Forest Park", "Forrest City", "Fort Collins", "Fort Dodge", "Fort Lauderdale", 
  "Fort Lee", "Fort Madison", "Fort Morgan", "Fort Myers", "Fort Pierce", "Fort Scott", "Fort Smith", 
  "Fort Walton Beach", "Fort Wayne", "Fort Worth", "Fortuna", "Fosston", "Fountain", "Fox Lake", "Framingham", 
  "Frankfort", "Franklin", "Frederick", "Freehold", "Freeport", "Fremont", "Fresno", "Frisco", "Fullerton", 
  "Gadsden", "Gaffney", "Gainesville", "Galax", "Galena", "Galesburg", "Gallatin", "Gallup", "Galveston", 
  "Garden City", "Garden Grove", "Gardena", "Gardner", "Garfield", "Garland", "Gatlinburg", "Geneva", 
  "Georgetown", "Germantown", "Gilbert", "Gilroy", "Glasgow", "Glassboro", "Glen Cove", "Glen Ellyn", 
  "Glendale", "Glendora", "Glenview", "Glenwood Springs", "Gloucester", "Godfrey", "Golden", "Goldsboro", 
  "Goose Creek", "Grand Forks", "Grand Haven", "Grand Island", "Grand Junction", "Grand Rapids", "Grandview", 
  "Granger", "Granite City", "Grants", "Grants Pass", "Grapevine", "Grass Valley", "Grayling", "Great Bend", 
  "Great Falls", "Greeley", "Green Bay", "Greenfield", "Greensboro", "Greensburg", "Greenville", "Greenwich", 
  "Greenwood", "Grenada", "Gresham", "Griffin", "Grosse Pointe", "Groton", "Grove City", "Groves", "Gulfport", 
  "Gunnison", "Guntersville", "Gurnee", "Hackensack", "Hagerstown", "Haines City", "Hallandale Beach", 
  "Hamden", "Hammond", "Hampton", "Hanford", "Hannibal", "Hanover", "Harlingen", "Harrisburg", "Harrison", 
  "Harrisonburg", "Hartford", "Hastings", "Hattiesburg", "Haverhill", "Hawthorne", "Hayward", "Hazleton", 
  "Helena", "Hemet", "Hempstead", "Henderson", "Hendersonville", "Henning", "Hermitage", "Hesperia", 
  "Hialeah", "Hibbing", "Hickory", "Highland", "Highland Park", "Hillsboro", "Hillsdale", "Hilo", "Hobbs", 
  "Hoboken", "Hoffman Estates", "Holbrook", "Holland", "Holly Springs", "Hollywood", "Holyoke", "Homer", 
  "Homestead", "Honolulu", "Hood River", "Hoover", "Hope", "Hopkinsville", "Hot Springs", "Houston", "Hudson", 
  "Hudsonville", "Humboldt", "Huntersville", "Huntington", "Huntington Beach", "Huntsville", "Huron", 
  "Hutchinson", "Hyattsville", "Idaho Falls", "Independence", "Indianapolis", "Indio", "Inglewood", "Iowa City", 
  "Iron Mountain", "Ironwood", "Irvine", "Irving", "Irvington", "Ishpeming", "Issaquah", "Jackson", "Jacksonville", 
  "Jamestown", "Janesville", "Jasper", "Jeannette", "Jefferson City", "Jeffersonville", "Jersey City", "Johnson City", 
  "Johnstown", "Joliet", "Jonesboro", "Joplin", "Junction City", "Juneau", "Jupiter", "Kahului", "Kalamazoo", 
  "Kalispell", "Kaneohe", "Kankakee", "Kansas City", "Kapaa", "Keene", "Keizer", "Keller", "Kemah", "Kenner", 
  "Kennesaw", "Kennewick", "Kenosha", "Kent", "Kentwood", "Kettering", "Key West", "Kihei", "Kilgore", "Killeen", 
  "King City", "Kingman", "Kings Mountain", "Kingston", "Kingsville", "Kirkland", "Kissimmee", "Kitty Hawk", 
  "Klamath Falls", "Knoxville", "Kodiak", "Kokomo", "La Crosse", "La Grange", "La Jolla", "La Mesa", "La Mirada", 
  "La Porte", "La Quinta", "Lacey", "Lafayette", "Laguna Beach", "Laguna Hills", "Laguna Niguel", "Lake Charles", 
  "Lake City", "Lake Elsinore", "Lake Forest", "Lake Havasu City", "Lake Jackson", "Lake Oswego", "Lake Wales", 
  "Lake Worth", "Lakeland", "Lakeport", "Lakeville", "Lakewood", "Lancaster", "Lansdale", "Lansing", "Laramie", 
  "Laredo", "Largo", "Las Cruces", "Las Vegas", "Laurel", "Lawrence", "Lawton", "Layton", "League City", "Lebanon", 
  "Leesburg", "Lehi", "Lenexa", "Lennox", "Leonia", "Lewiston", "Lewisville", "Lexington", "Liberal", "Lima", 
  "Lincoln", "Lincoln Park", "Linden", "Livermore", "Livonia", "Lockport", "Lodi", "Logan", "Lombard", "Lompoc", 
  "Long Beach", "Longmont", "Longview", "Lorain", "Los Alamos", "Los Angeles", "Los Banos", "Los Gatos", "Louisville", 
  "Loveland", "Lowell", "Lubbock", "Ludington", "Lugoff", "Lumberton", "Lynchburg", "Lynn", "Lynnwood", "Macon", 
  "Madison", "Madera", "Malden", "Manchester", "Manhattan", "Mankato", "Mansfied", "Manteca", "Maple Grove", 
  "Maplewood", "Marblehead", "Marietta", "Marion", "Marlborough", "Marquette", "Marshall", "Martinez", "Marysville", 
  "Mason", "Mason City", "Massillon", "McAlester", "McAllen", "McComb", "Medford", "Medicine Lodge", "Melbourne", 
  "Memphis", "Menlo Park", "Menomonie", "Mentor", "Merced", "Meriden", "Meridian", "Mesa", "Mesquite", "Metairie", 
  "Miami", "Miami Beach", "Michigan City", "Middletown", "Midland", "Milford", "Millville", "Milton", "Milwaukee", 
  "Minneapolis", "Minnetonka", "Minot", "Missoula", "Mobile", "Modesto", "Moline", "Monroe", "Monroeville", 
  "Montclair", "Monterey", "Monterey Park", "Montgomery", "Moorhead", "Moorpark", "Moreno Valley", "Morgan Hill", 
  "Morgantown", "Morris", "Morristown", "Moses Lake", "Moultrie", "Mount Clemens", "Mount Pleasant", "Mount Prospect", 
  "Mount Vernon", "Mountain Home", "Mountain View", "Muncie", "Munster", "Murfreesboro", "Murrieta", "Muscatine", 
  "Muskegon", "Muskogee", "Nacogdoches", "Nampa", "Nantucket", "Napa", "Naples", "Nashua", "Nashville", "Natchez", 
  "Natick", "Naugatuck", "Needham", "Nesquehoning", "Nevada", "New Bedford", "New Bern", "New Braunfels", "New Brighton", 
  "New Britain", "New Brunswick", "New Haven", "New Iberia", "New London", "New Orleans", "New Paltz", "New Philadelphia", 
  "New Rochelle", "New Ulm", "New York", "Newark", "Newberg", "Newburgh", "Newburyport", "Newcastle", "Newport", 
  "Newport Beach", "Newport News", "Newton", "Niagara Falls", "Niceville", "Niles", "Norfolk", "Normal", "Norman", 
  "North Adams", "North Charleston", "North Las Vegas", "North Little Rock", "North Miami", "North Miami Beach", 
  "North Platte", "North Port", "Northampton", "Northfield", "Northglenn", "Novato", "Novi", "Oak Harbor", "Oak Lawn", 
  "Oak Park", "Oakland", "Ocala", "Ocean City", "Ocean Springs", "Oceanside", "Odessa", "Ogden", "O'Fallon", 
  "Oil City", "Ojai", "Oklahoma City", "Okmulgee", "Olathe", "Olean", "Olympia", "Omaha", "Ontario", "Orange", 
  "Orangeburg", "Orem", "Orlando", "Ormond Beach", "Oro Valley", "Oroville", "Osage Beach", "Oshkosh", "Oskaloosa", 
  "Ossining", "Oswego", "Ottawa", "Ottumwa", "Overland Park", "Owatonna", "Owensboro", "Oxford", "Oxnard", 
  "Pacifica", "Pacific Grove", "Paducah", "Palo Alto", "Panama City", "Paradise", "Paramount", "Park City", 
  "Park Forest", "Park Ridge", "Parker", "Parkersburg", "Parkville", "Parsons", "Pasadena", "Pasco", "Paso Robles", 
  "Passaic", "Paterson", "Pawtucket", "Peabody", "Peachtree City", "Pecos", "Pelham", "Pendleton", "Pensacola", 
  "Peoria", "Perth Amboy", "Petaluma", "Petersburg", "Pflugerville", "Pharr", "Phenix City", "Philadelphia", 
  "Phoenix", "Picayune", "Pierre", "Pine Bluff", "Pinellas Park", "Pipestone", "Piqua", "Pittsburg", "Pittsburgh", 
  "Pittsfield", "Placentia", "Plainfield", "Plainview", "Plano", "Plattsburgh", "Plattsmouth", "Pleasant Grove", 
  "Pleasant Hill", "Pleasanton", "Plymouth", "Pocatello", "Point Pleasant", "Pompano Beach", "Ponca City", "Pontiac", 
  "Port Angeles", "Port Arthur", "Port Charlotte", "Port Hueneme", "Port Huron", "Port Jefferson", "Port Jervis", 
  "Port Orange", "Port Orchard", "Port St. Lucie", "Port Townsend", "Port Washington", "Portage", "Portales", 
  "Porterville", "Portland", "Portsmouth", "Pottstown", "Pottsville", "Poughkeepsie", "Prescott", "Prescott Valley", 
  "Presque Isle", "Princeton", "Prineville", "Providence", "Provo", "Pueblo", "Pullman", "Punta Gorda", "Purcellville", 
  "Putnam", "Quakertown", "Quincy", "Racine", "Rahway", "Raleigh", "Rancho Cordova", "Rancho Cucamonga", "Randolph", 
  "Rantoul", "Rapid City", "Reading", "Red Bank", "Red Bluff", "Red Wing", "Redding", "Redford", "Redlands", 
  "Redmond", "Redondo Beach", "Redwood City", "Reedley", "Reno", "Rensselaer", "Renton", "Reston", "Revere", 
  "Rexburg", "Reynoldsburg", "Richmond", "Ridgecrest", "Ridgeland", "Ridgewood", "Rifle", "Rio Rancho", "Ripon", 
  "River Falls", "River Forest", "River Rouge", "Riverdale", "Riverside", "Riverton", "Roanoke", "Rochester", 
  "Rock Hill", "Rock Island", "Rock Springs", "Rockford", "Rockland", "Rockville", "Rogers", "Rolla", "Rolling Meadows", 
  "Rome", "Romeoville", "Romulus", "Roseburg", "Roselle", "Rosemead", "Roseville", "Roswell", "Rothschild", "Rotterdam", 
  "Rowlett", "Royal Oak", "Royalton", "Rubidoux", "Rugby", "Ruston", "Rutland", "Rye", "Sacramento", "Saginaw", 
  "Salamanca", "Salem", "Salida", "Salina", "Salinas", "Salisbury", "Salt Lake City", "Sammamish", "San Angelo", 
  "San Antonio", "San Bernardino", "San Bruno", "San Buenaventura", "San Carlos", "San Clemente", "San Diego", 
  "San Dimas", "San Fernando", "San Francisco", "San Gabriel", "San Jose", "San Juan Capistrano", "San Leandro", 
  "San Luis Obispo", "San Marcos", "San Mateo", "San Pedro", "San Rafael", "San Ramon", "Sandy", "Sandy Springs", 
  "Sanford", "Sanibel", "Santa Ana", "Santa Barbara", "Santa Clara", "Santa Clarita", "Santa Cruz", "Santa Fe", 
  "Santa Maria", "Santa Monica", "Santa Paula", "Santa Rosa", "Santee", "Sarasota", "Saratoga", "Saratoga Springs", 
  "Saugus", "Savannah", "Sayre", "Scarborough", "Scarsdale", "Schenectady", "Scottsbluff", "Scottsdale", "Scranton", 
  "Searcy", "Seattle", "Sebring", "Sedalia", "Sedona", "Selma", "Seminole", "Sevierville", "Sewanee", "Seward", 
  "Seymour", "Shaker Heights", "Shawnee", "Sheboygan", "Sheffield", "Shelby", "Shelbyville", "Shelton", "Shenandoah", 
  "Shepherdsville", "Sheridan", "Sherman", "Shiloh", "Shreveport", "Sidney", "Sierra Vista", "Sikeston", "Silver City", 
  "Silver Spring", "Silverthorne", "Simi Valley", "Simpsonville", "Sioux City", "Sioux Falls", "Skokie", "Slidell", 
  "Smyrna", "Socorro", "Solana Beach", "Somerset", "Somerville", "Sonoma", "Sonora", "South Bend", "South Gate", 
  "South Haven", "South Lake Tahoe", "South Lyon", "South Miami", "South Padre Island", "South Pasadena", "South Portland", 
  "South San Francisco", "Southaven", "Southfield", "Southington", "Spanish Fork", "Sparks", "Spartanburg", "Spearfish", 
  "Spokane", "Springdale", "Springfield", "Stamford", "Starkville", "State College", "Statesboro", "Staunton", "Steamboat Springs", 
  "Sterling", "Sterling Heights", "Stevens Point", "Stillwater", "Stockton", "Stonington", "Stoughton", "Stow", "Stratford", 
  "Stroudsburg", "Stuart", "Sturgeon Bay", "Sturgis", "Sudbury", "Suffolk", "Sulphur Springs", "Summerville", "Summit", 
  "Sumter", "Sun City", "Sun Prairie", "Sun Valley", "Sunny Isles Beach", "Sunnyvale", "Superior", "Surprise", "Sweet Home", 
  "Sweetwater", "Sycamore", "Syracuse", "Tacoma", "Tallahassee", "Tamarac", "Tampa", "Taneytown", "Tarboro", "Tarpon Springs", 
  "Tarrytown", "Taunton", "Taylor", "Teaneck", "Tehachapi", "Temecula", "Tempe", "Temple", "Terre Haute", "Texarkana", 
  "Texas City", "The Dalles", "The Villages", "Thomasville", "Thornton", "Thousand Oaks", "Three Rivers", "Tiffin", "Tifton", 
  "Tillamook", "Titusville", "Toledo", "Tombstone", "Topeka", "Torrance", "Torrington", "Traverse City", "Trenton", "Troy", 
  "Tucson", "Tullahoma", "Tulsa", "Tupelo", "Turlock", "Tuscaloosa", "Tustin", "Twin Falls", "Tyler", "Ukiah", "Union City", 
  "Uniontown", "Upper Arlington", "Urbana", "Utica", "Vacaville", "Valdosta", "Vallejo", "Valley City", "Valparaiso", 
  "Vancouver", "Venice", "Ventura", "Vermillion", "Vero Beach", "Vicksburg", "Victoria", "Victorville", "Vincennes", 
  "Vineland", "Virginia Beach", "Visalia", "Vista", "Wabash", "Waco", "Wahpeton", "Waianae", "Wailuku", "Waimea", 
  "Walla Walla", "Wallingford", "Walnut Creek", "Walsenburg", "Waltham", "Wapakoneta", "Warner Robins", "Warren", 
  "Warrensburg", "Warwick", "Washington", "Waterbury", "Waterford", "Waterloo", "Watertown", "Waterville", "Watsonville", 
  "Waukegan", "Waukesha", "Wausau", "Wauwatosa", "Waverly", "Wayne", "Waynesboro", "Weatherford", "Webster", "Weed", 
  "Wellesley", "Wenatchee", "West Allis", "West Bend", "West Bloomfield", "West Chester", "West Covina", "West Des Moines", 
  "West Hartford", "West Haven", "West Hollywood", "West Jordan", "West Lafayette", "West Linn", "West Memphis", 
  "West New York", "West Orange", "West Palm Beach", "West Plains", "West Point", "West Sacramento", "West Springfield", 
  "West Valley City", "Westbrook", "Westerly", "Westerville", "Westfield", "Westminster", "Weston", "Westport", "Westwood", 
  "Wheaton", "Wheeling", "White Plains", "White River Junction", "White Springs", "Whitehall", "Whitewater", "Wichita", 
  "Wichita Falls", "Wilkes-Barre", "Williamsburg", "Williamsport", "Williamstown", "Willimantic", "Williston", "Willmar", 
  "Willoughby", "Wilmette", "Wilmington", "Wilson", "Winchester", "Windsor", "Winfield", "Winnemucca", "Winona", 
  "Winston-Salem", "Winter Garden", "Winter Haven", "Winter Park", "Wisconsin Dells", "Woburn", "Woodbury", "Woodland", 
  "Woodstock", "Woodward", "Woonsocket", "Wooster", "Worcester", "Worthington", "Wyandotte", "Wyoming", "Xenia", 
  "Yakima", "Yankton", "Yardley", "Yarmouth", "Yonkers", "Yorktown", "Youngstown", "Ypsilanti", "Yuba City", "Yucaipa", 
  "Yucca Valley", "Yuma", "Zanesville", "Zeeland", "Zion"
];